<div class="regulamento-fullscreen">
  <div class="regulamento-areautil">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="regulamento-box">
            <a href="javascript: void(0);" class="btn-close btn-fechar-regulamento"><i class="fa fa-times" aria-hidden="true"></i></a>

            <h1 class="page__title">Regulamento</h1>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut auctor velit, tempus accumsan leo. Nullam rhoncus tincidunt placerat. Etiam ut pretium nulla. Praesent accumsan dapibus blandit. Ut vel magna ante. Sed eu libero est. Proin suscipit elit metus, sit amet malesuada ex egestas sed. Sed enim mi, lobortis a luctus in, pulvinar in eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus massa sed massa sagittis, et iaculis lorem hendrerit. Nullam non nisl id nulla hendrerit pretium a quis diam. Nullam pulvinar in augue quis posuere. In efficitur arcu eget leo hendrerit, in ultricies urna pulvinar. Praesent convallis nulla arcu, non euismod ligula pharetra id. Maecenas arcu quam, laoreet a eros id, imperdiet venenatis metus. Donec at ullamcorper metus.</p>
            <p>Nullam mollis ut elit imperdiet vehicula. Ut eget justo et mauris egestas vehicula vitae condimentum quam. Curabitur commodo ante nec urna venenatis aliquam. Aliquam erat volutpat. Nunc in maximus odio. Quisque mauris velit, suscipit non gravida sed, tristique maximus dolor. Phasellus nec rutrum arcu, a dapibus sem. Cras posuere in libero vel hendrerit. Mauris dictum rhoncus consequat.</p>
            <p>Proin dictum magna quis laoreet vehicula. Donec egestas eget tellus id aliquam. Vestibulum turpis metus, porta sit amet tincidunt a, congue eu tortor. Duis tincidunt est lacus, nec iaculis lorem semper ornare. In commodo a magna in iaculis. Ut feugiat tincidunt enim, ac luctus diam euismod eu. Etiam vestibulum mi sed vestibulum volutpat. Fusce id gravida erat. Pellentesque porta elementum lacinia. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nam congue quis quam maximus euismod.</p>
            <p>Proin auctor magna ac egestas luctus. Nam eget ex sed enim laoreet faucibus et vel mi. Nunc commodo sapien vestibulum faucibus pharetra. Maecenas eu sapien eu neque posuere aliquam. Maecenas pretium magna a mauris pharetra, sagittis euismod nisl semper. Integer tincidunt, dui eget consectetur sollicitudin, ex ligula dignissim massa, in porta nisi nulla malesuada risus. Maecenas auctor porta sollicitudin. Etiam ut efficitur dolor, ultricies efficitur metus. Quisque quis dui ac quam commodo pulvinar. Vivamus finibus, augue ac suscipit imperdiet, purus ex gravida nisl, congue suscipit diam sapien in ex. Fusce venenatis libero nec nibh placerat, ac egestas dolor lacinia. Proin id placerat velit. Nulla elementum, justo vel ultrices varius, purus tellus lobortis est, convallis efficitur tortor nunc at enim. In in risus arcu.</p>
            <p>Praesent ac lectus tristique nibh varius ultricies vitae non neque. In eget dui vulputate, varius neque sed, aliquam nisi. Aliquam pretium tortor vitae mi ultrices lacinia. In lorem eros, pulvinar vitae sem nec, egestas fermentum augue. Cras ultricies erat consectetur mollis varius. Quisque ultrices sapien mi, ac tempor urna porta ac. Sed nec tellus sagittis, condimentum ipsum nec, mollis augue. Phasellus vestibulum ipsum non ipsum egestas mattis. Aenean tincidunt libero lorem, a bibendum dui viverra a. Proin dictum, ligula et tempus faucibus, felis ligula rhoncus neque, quis venenatis tortor tellus sed ex. Vivamus gravida metus vitae augue vehicula posuere.</p>
            <p>Nullam lectus enim, eleifend vel risus in, aliquet iaculis dui. Suspendisse sit amet dolor aliquet, imperdiet arcu non, scelerisque ante. Vivamus eget urna luctus, porta augue eu, consequat urna. Nam id mattis metus. Integer pellentesque sapien feugiat elit mollis, sit amet maximus tortor aliquet. Sed mollis lacinia urna ut sodales. Phasellus rhoncus, enim eget sodales lacinia, ex tortor sagittis ante, sit amet ultrices tortor turpis sed justo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas eget sollicitudin augue. Maecenas eget mollis mi.</p>
            <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc non augue sit amet sem commodo faucibus. In hac habitasse platea dictumst. Ut ultricies pellentesque iaculis. In pharetra urna ipsum, sed consequat diam pharetra vitae. Vestibulum nisl mi, bibendum eget quam ac, aliquam scelerisque nunc. Maecenas non euismod mauris. Suspendisse potenti. Sed tristique turpis vitae ligula convallis porta. Fusce et rutrum ligula.</p>
            <p>Aenean lectus elit, maximus faucibus consectetur ac, facilisis sit amet ex. Aenean et lacus nulla. Vestibulum at sem vitae sapien faucibus luctus. Nullam pulvinar condimentum semper. Duis erat nisi, venenatis ut dolor quis, convallis pharetra magna. Vivamus consequat ligula et orci convallis interdum. Morbi blandit est at dolor ultrices, pharetra consequat eros tincidunt. Nulla egestas id magna in imperdiet. Nullam congue venenatis ex, quis pulvinar enim cursus sed. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean sed ultrices lorem. Phasellus venenatis ligula at vestibulum vehicula.</p>
            <p>Fusce congue arcu ac quam tempor, id mollis est porta. Nulla non ipsum fringilla, pellentesque odio non, dictum ipsum. Sed quis felis sit amet ipsum congue egestas. Mauris diam ante, faucibus vel laoreet nec, placerat at lectus. Etiam vestibulum risus sit amet lorem hendrerit lacinia at vel orci. Curabitur arcu dui, facilisis non leo eget, pulvinar eleifend mauris. Proin quis semper lacus. Sed pulvinar nisl sem, sit amet luctus tortor varius sed. Sed pharetra pulvinar vulputate. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
            <p>Praesent nec massa pharetra, laoreet lacus id, consectetur magna. Nullam eu tellus ut neque gravida efficitur. Quisque vestibulum orci augue, at condimentum velit malesuada et. Sed finibus, velit nec auctor faucibus, odio sapien laoreet orci, et aliquam mauris lorem eget nisi. Nam vehicula tincidunt aliquam. In semper placerat magna, accumsan dapibus ante facilisis eget. Aenean sed tincidunt odio. Phasellus nec lectus in eros ultricies pretium vitae quis arcu. Duis elementum lacus a malesuada aliquam. Proin scelerisque ornare quam. In lobortis, nunc ut laoreet malesuada, tellus mauris fermentum dui, tempus sodales metus leo id erat. Mauris massa nulla, lacinia nec tincidunt sit amet, sagittis quis odio. Fusce non nunc lacinia, scelerisque libero vel, gravida dolor. Etiam placerat quam porttitor scelerisque blandit. Sed tincidunt tellus turpis, vel convallis nibh sollicitudin a.</p>
            <p>Fusce sit amet libero auctor, porttitor eros in, ultrices arcu. Mauris at sollicitudin mauris. Pellentesque egestas massa massa, vel commodo magna semper vitae. Duis a dolor ultrices, pellentesque erat at, eleifend lorem. Fusce non metus vel ipsum dignissim dapibus nec ac arcu. Sed in odio finibus, aliquam sapien ac, hendrerit turpis. Proin sollicitudin neque nec metus ullamcorper scelerisque. Proin condimentum molestie elit quis ullamcorper. Aenean eleifend tellus mauris, bibendum feugiat ante iaculis finibus. Maecenas ultrices placerat sem, nec porttitor ante sagittis in. In egestas nisi et enim interdum pellentesque. Vestibulum id enim enim.</p>
            <p>Ut nulla ex, pellentesque luctus lacus eu, fermentum vulputate velit. Suspendisse at lectus vel nulla auctor tincidunt. Aenean tincidunt convallis facilisis. Nulla et diam metus. Nullam ut sem enim. Sed in porta velit. Mauris vel nisi id tortor lobortis lobortis. Ut vel massa bibendum odio vulputate consequat vitae sed risus. Nullam ut arcu ante. Curabitur aliquam diam sit amet sem aliquam placerat. Suspendisse tristique aliquet augue, at suscipit nulla maximus at. Curabitur lorem quam, luctus accumsan sollicitudin aliquam, venenatis sed lacus. Morbi bibendum massa eget laoreet rutrum. Sed metus urna, imperdiet nec risus varius, lobortis ultrices nulla.</p>
            <p>Suspendisse condimentum eget nulla at tempus. Vestibulum suscipit velit ut lectus sagittis aliquet vitae id est. Praesent pretium mi tempus hendrerit cursus. Ut posuere cursus lacus, at varius risus euismod tempus. Nulla pellentesque neque ac lacus laoreet, sit amet vulputate tortor malesuada. Ut lorem metus, congue interdum condimentum in, semper vel quam. Nulla posuere diam a dignissim fermentum. Sed eleifend mollis justo, ac varius urna commodo eget. In hac habitasse platea dictumst. Aenean tristique, sapien vel tincidunt placerat, leo ipsum rutrum arcu, ut mollis urna dolor eu est. Donec gravida eget nisl sit amet auctor. Duis faucibus mi ac magna interdum, id ultrices metus cursus. Praesent ut erat ligula. Donec sed pellentesque nisl.</p>
            <p>Donec dapibus consequat molestie. Aenean odio nisi, consectetur id aliquam sit amet, semper at nulla. Etiam lacus ligula, ornare vel nulla eget, efficitur tempus justo. Quisque consequat eros a hendrerit cursus. Nullam sollicitudin, massa et varius auctor, tellus justo pellentesque leo, in porta eros elit sit amet felis. Suspendisse luctus nibh sed erat aliquam bibendum. Pellentesque vehicula diam vel venenatis elementum.</p>
            <p>Etiam nec leo et felis fermentum dictum non ut magna. Suspendisse convallis tristique rutrum. Cras condimentum condimentum semper. Integer pharetra augue sed velit eleifend pharetra in sed mauris. Mauris accumsan risus ac turpis mollis auctor. Fusce et dictum velit, ut pulvinar leo. Ut quis semper augue, vel posuere orci. Praesent eget purus vel odio ultricies imperdiet. Sed tincidunt quam in dapibus rutrum. Aliquam nec erat ut lacus iaculis dapibus. Quisque blandit sapien sed mauris facilisis, nec fermentum dui eleifend. Etiam diam magna, vulputate eu nulla in, convallis fringilla nisl. Vivamus a massa justo.</p>
            <p>Aliquam vitae mi viverra, volutpat enim sed, fringilla est. Praesent placerat facilisis eleifend. Phasellus ex metus, dictum sed metus a, accumsan varius erat. Pellentesque aliquet dapibus gravida. Nullam nec hendrerit lacus. Aenean et enim enim. Suspendisse potenti. In sagittis quis lacus ac pellentesque. Curabitur tincidunt vestibulum eros nec pellentesque. Vivamus purus turpis, fermentum quis turpis quis, fermentum fringilla leo. Praesent id mollis est, vitae vehicula mi. In rutrum vitae orci eu tempor.</p>
            <p>In id orci lectus. Phasellus justo justo, finibus ac felis sit amet, sodales mattis ipsum. Ut nec interdum urna, vitae maximus arcu. Vivamus auctor porttitor ex, at efficitur velit tempor at. Vestibulum consectetur mi ac luctus mollis. Nulla porttitor efficitur ligula. Maecenas nec diam ac sem dapibus consequat. Nunc ullamcorper molestie tincidunt. In in neque suscipit, rhoncus lectus at, finibus neque. Sed erat tellus, congue sed mollis sed, interdum sit amet eros.</p>
            <p>Cras non lorem non magna aliquam iaculis. Aliquam urna felis, faucibus fermentum porta id, sollicitudin et metus. Suspendisse molestie hendrerit felis id eleifend. Phasellus sed ante ut arcu imperdiet sagittis ut sed quam. Nullam congue nisl vel diam maximus commodo. Nulla tristique porttitor mollis. Nam in ornare orci, ac pellentesque velit. Praesent nec laoreet sapien. Cras lacus ipsum, laoreet at eros sagittis, feugiat aliquam leo.</p>
            <p>Pellentesque tristique felis mauris, at mollis libero ornare eu. Donec ac quam cursus, ultricies arcu porttitor, faucibus tortor. Vivamus congue quis metus volutpat dictum. Nunc ut nunc dolor. Phasellus tempor, ante vitae volutpat ultricies, est ligula molestie mi, a varius purus lorem ac elit. Duis a auctor dolor. Donec nec diam ex. Mauris non dolor eget tellus viverra hendrerit et sed diam. Nulla vel accumsan sem.</p>
            <p>Nulla imperdiet finibus dolor, a egestas leo lacinia vitae. Curabitur lobortis nibh at bibendum blandit. Donec nec erat nulla. Mauris efficitur libero magna, quis commodo arcu tincidunt id. Ut fringilla ac tortor quis pharetra. Phasellus nec leo pellentesque tellus elementum convallis eget aliquet sapien. Ut sapien diam, rhoncus sit amet arcu nec, placerat interdum justo. Aliquam fringilla finibus urna, at porta erat pulvinar ac. Nunc tempus, nulla id finibus vehicula, justo ex pulvinar arcu, nec euismod leo lectus in ante. Nulla metus ex, sagittis quis venenatis a, hendrerit eget tortor. Duis eget accumsan felis, nec sodales est. Nunc posuere, tellus at luctus suscipit, turpis quam tincidunt nulla, eu aliquet mauris tortor ac neque. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse consequat aliquam scelerisque. Sed finibus purus et tincidunt rutrum.</p>
            <p>Etiam interdum porta vehicula. Sed maximus molestie accumsan. In et mauris ac nibh euismod mattis ut sit amet magna. Donec pulvinar blandit lacus, et sagittis sem semper vel. Pellentesque vulputate eleifend massa sed bibendum. Sed a commodo ex, nec aliquet augue. Nulla varius mattis est, vel vulputate eros posuere eget. Praesent nec metus elit. Aenean hendrerit elit sit amet neque vestibulum convallis. Quisque quam mauris, blandit non efficitur et, viverra quis nibh. Nullam dignissim sapien ut neque malesuada, in molestie purus fermentum. Pellentesque at sem leo. In rutrum placerat massa, et aliquam tellus eleifend sed. Cras eleifend leo vitae maximus blandit.</p>
            <p>Pellentesque malesuada hendrerit nunc, nec eleifend sapien scelerisque in. Curabitur pellentesque, orci a porta dapibus, odio magna fermentum eros, ac maximus quam leo et risus. Duis ullamcorper neque vel nunc interdum maximus. Curabitur blandit imperdiet quam, at cursus est aliquet non. Sed eu nibh turpis. In mauris erat, lobortis ac bibendum non, blandit quis tortor. Sed quis eros ac ex eleifend viverra. Cras tincidunt porttitor aliquet.</p>
            <p>Integer sit amet pharetra ligula, eget porttitor ligula. Praesent elit tortor, tincidunt ut volutpat id, placerat sed magna. Morbi accumsan metus blandit est luctus sollicitudin sit amet eu mi. Integer elit sem, pharetra ac elit id, interdum cursus ipsum. Fusce quis venenatis nisl. Proin ut mauris vel nunc condimentum fringilla sit amet ut justo. Cras eget nunc rutrum, mollis ligula quis, rhoncus tellus. Cras non lorem nulla.</p>
            <p>Pellentesque vitae odio fringilla, lacinia risus in, egestas risus. Nullam id magna eu augue tempus malesuada non consequat augue. Nunc bibendum nisi ante, nec aliquet nisi eleifend et. Sed aliquet dolor a felis tempor, at aliquet enim interdum. Quisque in purus dignissim erat rutrum malesuada in nec risus. Sed feugiat eu ligula in maximus. Fusce a mollis tortor. Curabitur ornare, ipsum nec cursus dictum, arcu purus suscipit sem, sit amet gravida sapien diam vel nisl. Mauris eget est consectetur, lobortis justo consequat, laoreet libero. Duis malesuada dolor sit amet enim pharetra, et congue arcu consectetur. Sed id ipsum sed lectus pharetra varius. Proin consequat, lectus non consectetur fermentum, neque dolor mattis nulla, non maximus nulla nisl id ex. Fusce nec placerat turpis.</p>
            <p>Phasellus eu volutpat turpis. Aliquam consequat porta nulla, vel hendrerit est aliquet at. Vivamus tincidunt id risus vel egestas. Suspendisse vel leo porttitor, tincidunt augue vel, tincidunt sapien. Fusce justo sem, lobortis sit amet nulla porttitor, ultrices porttitor libero. Suspendisse potenti. Aenean est magna, mattis a turpis eget, tincidunt egestas orci. Mauris vel ipsum hendrerit, eleifend risus vel, viverra quam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut vitae maximus massa. Aenean suscipit mi neque, quis porttitor tortor imperdiet vestibulum. Fusce in eros dolor. Donec vestibulum scelerisque ipsum eget dapibus. Cras elementum, nunc vel suscipit iaculis, nisl quam tempus nisi, et efficitur turpis turpis vel ligula.</p>
            <p>Pellentesque vulputate velit nec nisl mattis, ac aliquet elit convallis. Cras tincidunt viverra placerat. Proin auctor libero ultricies tempus bibendum. Maecenas consequat felis ac justo vulputate, non convallis tortor porta. Nullam rutrum, arcu mollis ullamcorper efficitur, nisl ligula porta eros, eget dignissim velit elit et metus. Aliquam vehicula purus non turpis interdum consectetur. Aenean ultrices, odio a sollicitudin suscipit, felis lacus blandit risus, vitae lobortis purus enim quis ante. Vivamus fermentum luctus ex bibendum faucibus.</p>
            <p>Nam ultrices mauris non dui consequat interdum. Integer ornare, enim non porta consectetur, purus urna eleifend justo, sit amet tempor metus arcu sit amet enim. Nam nec nulla cursus est vestibulum ornare. Aenean finibus lacus eu tortor porttitor tempor vitae at nulla. Donec enim felis, commodo sollicitudin justo ut, rutrum porta sem. Morbi ultrices nisl eu malesuada viverra. Nullam varius volutpat odio, ut facilisis nisi luctus sit amet. Cras quis tristique ligula. Praesent mollis mauris at sollicitudin dignissim. Curabitur auctor dui sed elit congue, eu vestibulum leo mollis.</p>
            <p>Vestibulum faucibus porttitor eros. Aenean commodo arcu interdum magna gravida finibus. Curabitur a lobortis elit, id dictum enim. Nam in erat viverra, varius ante at, sollicitudin lectus. Vestibulum suscipit, orci eget vestibulum fermentum, nulla nunc suscipit enim, nec elementum dolor mauris eu turpis. Nulla imperdiet facilisis urna ut tempor. Nullam et mi ac tortor maximus auctor. Aenean hendrerit urna non augue viverra tempor. Suspendisse a ornare neque. Donec interdum massa quis ex pellentesque, id feugiat diam gravida. Etiam aliquet ultricies quam, id venenatis arcu pulvinar sit amet.</p>
            <p>Quisque scelerisque convallis urna eget consectetur. Pellentesque quis mi non sem porta vestibulum sit amet et arcu. Proin quis lacus sed sem commodo ultrices. Phasellus dictum felis at nibh varius, sed tincidunt ipsum rhoncus. Maecenas a erat sit amet orci porttitor hendrerit. Fusce efficitur rhoncus libero et tristique. Etiam diam erat, faucibus nec auctor eu, luctus id nibh. Quisque bibendum felis eu lacinia laoreet. Quisque lacinia, ipsum id tincidunt tempor, diam turpis tincidunt dolor, sit amet accumsan mauris augue eu dui. Cras leo nulla, ullamcorper ut porta eu, tempus id odio. Proin non dapibus risus, a rutrum velit. Fusce a ligula eu tortor scelerisque elementum nec scelerisque diam.</p>
            <p>Vivamus volutpat id nibh dapibus luctus. Praesent eleifend vestibulum nisl, a fermentum tortor malesuada non. Donec ultrices quam ut neque malesuada fringilla. Nunc magna sem, placerat vel enim non, cursus cursus purus. Vestibulum ut ipsum non ipsum pellentesque condimentum. Curabitur aliquet lacus elit. Maecenas sodales vitae justo eu aliquet. Duis aliquet non diam quis pellentesque. Vivamus nec libero mattis, tincidunt metus sit amet, mattis enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In tempor quam in ante convallis, eget venenatis sem lobortis. Proin eget purus consectetur, porta sapien vitae, fermentum tellus. Phasellus volutpat sollicitudin lorem, a scelerisque est accumsan vel.</p>

            <div class="text-center">
              <a href="javascript: void(0);" class="btn btn-grey-transparent btn-fechar-regulamento">Fechar</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>